start-at-login = true
after-login-command = []

# Color borders of active window
# Note: This does not work. Uses JankyBorders
# configured in ~/.config/borders/bordersrc
# Start manually: brew services start borders
# after-startup-command = [
#   'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0'
# ]

# Padding for tiles on top of each other
accordion-padding = 20

# Disable hide application shortcut (cmd-h)
automatically-unhide-macos-hidden-apps = true

# Gaps to show borders
[gaps]
inner.horizontal = 5
inner.vertical = 5
outer.left = 5
outer.bottom = 5
outer.top = 5
outer.right = 5

# 'main' binding mode
[mode.main.binding]
# Change layout
alt-i = 'layout tiles horizontal vertical'
alt-o = 'layout accordion horizontal'
alt-u = 'layout floating tiling'

# Change focus
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Switch to secondary monitor workspace
alt-z = 'workspace S1'

# Move window
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Workspaces
alt-a = 'workspace W1'
alt-s = 'workspace W2'
alt-d = 'workspace W3'
alt-f = 'workspace W4'
alt-g = 'workspace W5'
alt-x = 'workspace W6'
alt-c = 'workspace W7'
alt-v = 'workspace W8'
alt-q = 'workspace P1'
alt-w = 'workspace P2'
alt-e = 'workspace P3'
alt-r = 'workspace P4'
alt-t = 'workspace P5'

# Move window to workspace
alt-shift-a = 'move-node-to-workspace W1'
alt-shift-s = 'move-node-to-workspace W2'
alt-shift-d = 'move-node-to-workspace W3'
alt-shift-f = 'move-node-to-workspace W4'
alt-shift-g = 'move-node-to-workspace W5'
alt-shift-x = 'move-node-to-workspace W6'
alt-shift-c = 'move-node-to-workspace W7'
alt-shift-v = 'move-node-to-workspace W8'
alt-shift-q = 'move-node-to-workspace P1'
alt-shift-w = 'move-node-to-workspace P2'
alt-shift-e = 'move-node-to-workspace P3'
alt-shift-r = 'move-node-to-workspace P4'
alt-shift-t = 'move-node-to-workspace P5'
alt-shift-z = 'move-node-to-workspace S1'

# Shortcuts to open new window
alt-n = 'exec-and-forget open -n /Applications/Google\ Chrome.app'
alt-m = 'exec-and-forget open -n /Applications/Cursor.app'
alt-comma = 'exec-and-forget open /System/Applications/Notes.app'
alt-period = 'exec-and-forget open ~'

# Change to new modes
alt-shift-semicolon = 'mode service'  # semicolon = ø
alt-quote = 'mode resize'  # quote = æ

[mode.service.binding]
h = 'focus left'
j = 'focus down'
k = 'focus up'
l = 'focus right'
alt-h = 'move left'
alt-j = 'move down'
alt-k = 'move up'
alt-l = 'move right'
alt-shift-h = ['join-with left', 'layout accordion horizontal', 'mode main']
alt-shift-j = ['join-with down', 'layout accordion horizontal', 'mode main']
alt-shift-k = ['join-with up', 'layout accordion horizontal', 'mode main']
alt-shift-l = ['join-with right', 'layout accordion horizontal', 'mode main']
alt-shift-r = ['flatten-workspace-tree', 'mode main']  # reset layout
esc = 'mode main'

[mode.resize.binding]
h = 'resize width -100'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +100'
r = 'balance-sizes'
esc = 'mode main'

[workspace-to-monitor-force-assignment]
W1 = 'main'
W2 = 'main'
W3 = 'main'
W4 = 'main'
W5 = 'main'
W6 = 'main'
W7 = 'main'
W8 = 'main'
P1 = 'main'
P2 = 'main'
P3 = 'main'
P4 = 'main'
P5 = 'main'
S1 = 'secondary'

# sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
#s = ['layout sticky tiling', 'mode main']

# Float Messages app by default
[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = 'layout floating'

# Float Finder by default
[[on-window-detected]]
if.app-id = 'com.apple.finder'
run = 'layout floating'

# Float Notes by default
[[on-window-detected]]
if.app-id = 'com.apple.Notes'
run = 'layout floating'
