#!/bin/bash

### Runs the app stack from the main repo with the same service set
### and shared images/volumes as the worktree script.
###
### Usage:
###   scripts/run-main.sh --up
###   scripts/run-main.sh --stop
###   scripts/run-main.sh --start
###   scripts/run-main.sh --down
###   scripts/run-main.sh --nuke
###   scripts/run-main.sh --rebuild

set -euo pipefail

function check_docker() {
    if ! command -v docker &>/dev/null; then
        echo "Error: Docker not installed" >&2
        exit 1
    fi
    if ! docker info &>/dev/null; then
        echo "Error: Docker daemon not running" >&2
        exit 1
    fi
}

if ! git rev-parse --show-toplevel &>/dev/null; then
    echo "Error: Not inside a git repository" >&2
    exit 1
fi
repo_root="$(git rev-parse --show-toplevel)"
project_name="$(basename "$repo_root")"
tmp_dir="${DEV_STACKS_DIR:-$HOME/work/tmp/dev-stacks}/$project_name"

command=""
rebuild=false

function usage() {
    echo "Usage: $0 --[up|stop|start|down|nuke] [--rebuild]"
    echo
    echo "Options:"
    echo "  --up                Create and start the stack (reuses existing images)"
    echo "  --stop              Stop running containers without removing them"
    echo "  --start             Start previously stopped containers"
    echo "  --down              Stop and remove containers and networks"
    echo "  --nuke              Remove all containers, volumes, and images"
    echo "  --rebuild           Rebuild container images before starting"
    echo "  --help              Show this help message"
    exit 1
}

# --- Override file generation ---

function generate_override() {
    mkdir -p "$tmp_dir"
    local override_file="$tmp_dir/docker-compose.dev.yml"

    cat > "$override_file" <<'YAML'
# Auto-generated by run-main.sh
# Do not edit — regenerated on each run.

services:
  router-autoupdate:
    image: ledidi-shared-router-autoupdate
    pull_policy: build

  admin:
    image: ledidi-shared-admin
    pull_policy: build
    depends_on: !override
      mysql:
        condition: service_healthy

  codelist:
    image: ledidi-shared-codelist
    pull_policy: build

YAML

    echo "$override_file"
}

# --- Docker compose helper ---

function dc() {
    docker compose \
        -f "$repo_root/docker-compose.yml" \
        -f "$tmp_dir/docker-compose.dev.yml" \
        "$@"
}

# --- Seed helper ---

function run_seed() {
    echo
    echo "Seeding data..."
    echo

    dc exec admin npm run docker:push-db-schema
    dc exec admin node build/test-data/setup-test-datasources

    echo "Seeding ATC codes in registries database..."
    dc exec registries sh -c 'POSTGRES_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/registries" npm run seed-atc'

    echo
    echo "Data seeded successfully."
    echo
}

# --- Prerequisites ---

function prerequisites_check() {
    check_docker
}

# --- Parse arguments ---

if [ "$#" -lt 1 ]; then
    usage
fi

for arg in "$@"; do
    case $arg in
    --up|--stop|--start|--down|--nuke)
        if [ -n "$command" ]; then
            echo "Error: Only one command allowed" >&2
            exit 1
        fi
        command="${arg#--}"
        ;;
    --rebuild)
        rebuild=true
        ;;
    --help)
        usage
        ;;
    *)
        echo "Unknown argument: $arg"
        usage
        ;;
    esac
done

if [ -z "$command" ]; then
    usage
fi

# --- Execute ---

prerequisites_check

dev_services="main-frontend router router-autoupdate postgres mysql admin codelist registries"

if [ "$command" = "up" ]; then
    if [ ! -f "$repo_root/services/apollo-router/supergraph.graphql" ]; then
        touch "$repo_root/services/apollo-router/supergraph.graphql"
    fi
    generate_override > /dev/null
    if [ "$rebuild" = true ]; then
        dc up --build -d --wait $dev_services
    else
        dc up -d --wait $dev_services
    fi

    run_seed

    echo "Stack is running at http://localhost:3001/en/registries"

elif [ "$command" = "stop" ]; then
    generate_override > /dev/null
    dc stop

elif [ "$command" = "start" ]; then
    generate_override > /dev/null
    dc start

elif [ "$command" = "down" ]; then
    generate_override > /dev/null
    dc down

elif [ "$command" = "nuke" ]; then
    echo "This will remove all containers, volumes, and images."
    read -r -p "Are you sure? (y/N): " confirm
    echo
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        echo "Nuke operation cancelled."
        exit 0
    fi
    generate_override > /dev/null
    dc down -v --rmi local --remove-orphans
    rm -rf "$tmp_dir"
    echo
    echo "Nuke operation completed."

else
    echo "Unknown command: $command"
    exit 1
fi
