#!/bin/bash

### Runs the full app stack from any worktree, isolated from other worktrees
### by port offsets and Docker project namespacing.
###
### Usage:
###   scripts/run-worktree.sh --up [--slot=N]
###   scripts/run-worktree.sh --down [--slot=N]
###   scripts/run-worktree.sh --nuke [--slot=N]
###   scripts/run-worktree.sh --status
###
### Each worktree gets a slot number (1-9) that determines its port offset.
### Slot 0 is reserved for the main repo's scripts/dev.

set -euo pipefail

function check_docker() {
    if ! command -v docker &>/dev/null; then
        echo "Error: Docker not installed" >&2
        exit 1
    fi
    if ! docker info &>/dev/null; then
        echo "Error: Docker daemon not running" >&2
        exit 1
    fi
}

if ! git rev-parse --show-toplevel &>/dev/null; then
    echo "Error: Not inside a git repository" >&2
    exit 1
fi
repo_root="$(git rev-parse --show-toplevel)"

project_name="$(basename "$repo_root")"
tmp_dir="${WORKTREE_TMP_DIR:-$HOME/work/tmp/dev-stacks}/$project_name"

command=""
slot=""
rebuild=false

function usage() {
    echo "Usage: $0 --[up|stop|start|down|nuke|status] [--slot=N]"
    echo
    echo "Options:"
    echo "  --up                Create and start the worktree stack (reuses existing images)"
    echo "  --stop              Stop running containers without removing them"
    echo "  --start             Start previously stopped containers"
    echo "  --down              Stop and remove containers and networks"
    echo "  --nuke              Remove all containers, volumes, and images for this worktree"
    echo "  --status            List all running worktree stacks"
    echo "  --rebuild           Rebuild container images before starting"
    echo "  --slot=N            Slot number (1-9). Auto-assigned (next available) if omitted."
    echo "  --help              Show this help message"
    exit 1
}

# --- Slot management ---

slot_file="$tmp_dir/worktree-slot"

function is_slot_in_use() {
    local s=$1
    local containers
    containers=$(docker ps -aq --filter "label=com.ledidi.worktree-slot=${s}" 2>/dev/null)
    [ -n "$containers" ]
}

function next_available_slot() {
    local lockdir="/tmp/worktree-slot.lock"
    local stale_seconds=30

    # Check for stale lock (older than 30 seconds)
    if [ -d "$lockdir" ]; then
        local lock_age
        if [[ "$OSTYPE" == darwin* ]]; then
            lock_age=$(( $(date +%s) - $(stat -f %m "$lockdir" 2>/dev/null || echo 0) ))
        else
            lock_age=$(( $(date +%s) - $(stat -c %Y "$lockdir" 2>/dev/null || echo 0) ))
        fi
        if [ "$lock_age" -gt "$stale_seconds" ]; then
            rmdir "$lockdir" 2>/dev/null || true
        fi
    fi

    # Try to acquire lock
    if ! mkdir "$lockdir" 2>/dev/null; then
        echo "Error: Another instance is allocating a slot. If this persists, run: rmdir $lockdir" >&2
        exit 1
    fi

    # Ensure lock is released on exit
    trap 'rmdir "$lockdir" 2>/dev/null' EXIT

    for s in $(seq 1 9); do
        if ! is_slot_in_use "$s"; then
            rmdir "$lockdir" 2>/dev/null
            trap - EXIT
            echo "$s"
            return
        fi
    done

    rmdir "$lockdir" 2>/dev/null
    trap - EXIT
    echo "Error: All slots (1-9) are in use." >&2
    exit 1
}

function save_slot() {
    mkdir -p "$tmp_dir"
    echo "$1" > "$slot_file"
}

function read_saved_slot() {
    if [ -f "$slot_file" ]; then
        cat "$slot_file"
    else
        echo ""
    fi
}

function clear_saved_slot() {
    rm -f "$slot_file"
}

function resolve_slot() {
    if [ -n "$slot" ]; then
        # Explicit --slot=N provided
        if ! [[ "$slot" =~ ^[1-9]$ ]]; then
            echo "Error: --slot must be a number between 1 and 9."
            exit 1
        fi
        echo "$slot"
        return
    fi

    # Check for a previously saved slot, but verify it's still ours
    local saved
    saved=$(read_saved_slot)
    if [ -n "$saved" ]; then
        if is_slot_in_use "$saved"; then
            echo "$saved"
            return
        else
            # Stale slot file — clear it and fall through to auto-assign
            clear_saved_slot
        fi
    fi

    # Auto-assign the next available slot
    if [ "$command" = "up" ]; then
        next_available_slot
    else
        echo "Error: No slot assigned yet. Run --up first or pass --slot=N." >&2
        exit 1
    fi
}

# --- Override file generation ---

function generate_override() {
    local s=$1
    local offset=$(( s * 100 ))
    mkdir -p "$tmp_dir"
    local override_file="$tmp_dir/docker-compose.worktree.yml"
    local router_config="$tmp_dir/router.docker.worktree.yaml"

    # Generate a worktree-specific router config with the correct CORS origin
    sed "s|http://localhost:3001|http://localhost:$(( 3001 + offset ))|g" \
        "$repo_root/services/apollo-router/router.docker.yaml" > "$router_config"

    cat > "$override_file" <<YAML
# Auto-generated by run-worktree.sh (slot $s, offset $offset)
# Do not edit — regenerated on each run.

services:
  main-frontend:
    labels:
      com.ledidi.worktree-slot: "${s}"
    environment:
      - VITE_APP_URL=http://localhost:$(( 3001 + offset ))
      - VITE_GRAPHQL_URI=http://localhost:$(( 4000 + offset ))
      - VITE_SURVEY_URL=http://localhost:$(( 3001 + offset ))/surveys
      - VITE_AGENT_SERVICE_URL=http://localhost:$(( 4007 + offset ))
    volumes: !override
      - $repo_root/apps/main-frontend/src:/apps/main-frontend/src:cached
      - $repo_root/services/studies/api:/services/studies/api:cached
      - $repo_root/services/admin/api:/services/admin/api:cached
    ports: !override
      - "$(( 3001 + offset )):3001"

  router:
    volumes: !override
      - $repo_root/services/apollo-router/supergraph.graphql:/dist/schema/supergraph.graphql
      - $tmp_dir/router.docker.worktree.yaml:/dist/config/router.yaml
    ports: !override
      - "$(( 4000 + offset )):4000"

  postgres:
    ports: !override
      - "$(( 5432 + offset )):5432"

  mysql:
    command: --default-authentication-plugin=mysql_native_password
    ports: !override
      - "$(( 3336 + offset )):3306"

  admin:
    depends_on: !override
      mysql:
        condition: service_healthy
    volumes: !override
      - $repo_root/services/admin/src:/app/services/admin/src
      - $repo_root/services/admin/api:/app/services/admin/api
      - $repo_root/services/admin/prisma-mysql:/app/services/admin/prisma-mysql
      - $repo_root/services/admin/prisma-pgsql:/app/services/admin/prisma-pgsql
    ports: !override
      - "$(( 4004 + offset )):4000"
      - "$(( 50004 + offset )):50051"
      - "$(( 9004 + offset )):9229"

  codelist:
    volumes: !override
      - $repo_root/services/codelist/src:/app/services/codelist/src
      - $repo_root/services/codelist/api:/app/services/codelist/api
      - $repo_root/services/codelist/prisma:/app/services/codelist/prisma
      - ~/.aws:/root/.aws:ro
    ports: !override
      - "$(( 4005 + offset )):4000"
      - "$(( 50005 + offset )):50051"

  registries:
    volumes: !override
      - $repo_root/services/registries/src:/app/services/registries/src
      - $repo_root/services/registries/api:/app/services/registries/api
      - $repo_root/services/registries/prisma:/app/services/registries/prisma
      - $repo_root/services/admin/api:/app/services/admin/api
      - $repo_root/services/codelist/api:/app/services/codelist/api
      - ~/.aws:/root/.aws:ro
    ports: !override
      - "$(( 4006 + offset )):4000"
      - "$(( 50006 + offset )):50051"
      - "$(( 4002 + offset )):4002"
YAML

    # Conditionally add services that may not exist in all branches
    if grep -qE '^\s+agent:' "$repo_root/docker-compose.yml" 2>/dev/null; then
        cat >> "$override_file" <<AGENT_YAML

  agent:
    ports: !override
      - "$(( 4007 + offset )):4000"
AGENT_YAML
    fi

    # Append networks section last
    cat >> "$override_file" <<NETWORKS_YAML

networks:
  default:
    name: default-network-wt-${s}
    driver: bridge
NETWORKS_YAML

    echo "$override_file"
}

# --- Compose service filtering ---

function available_services() {
    local all_services="$1"
    local result=""
    for svc in $all_services; do
        if grep -qE "^\s+${svc}:" "$repo_root/docker-compose.yml" 2>/dev/null; then
            result="$result $svc"
        fi
    done
    echo "$result"
}

# --- Docker compose helper ---

function dc() {
    COMPOSE_PROJECT_NAME="$project_name" \
        docker compose \
        -f "$repo_root/docker-compose.yml" \
        -f "$tmp_dir/docker-compose.worktree.yml" \
        "$@"
}

# --- Lockfile freshness check ---

function check_image_freshness() {
    local image=$1
    local lockfile=$2

    if ! docker image inspect "$image" &>/dev/null; then
        return  # Image doesn't exist yet; will be built on first up
    fi

    if [ ! -f "$lockfile" ]; then
        return
    fi

    local current_hash
    current_hash=$(md5 -q "$lockfile" 2>/dev/null || md5sum "$lockfile" | cut -d' ' -f1)

    local hash_file="$tmp_dir/${image}.lockfile-hash"
    local stored_hash=""
    if [ -f "$hash_file" ]; then
        stored_hash=$(cat "$hash_file")
    fi

    if [ "$current_hash" != "$stored_hash" ]; then
        echo "Dependencies changed for $image — forcing rebuild."
        rebuild=true
    fi
}

function save_lockfile_hashes() {
    local pairs=(
        "${project_name}-admin:$repo_root/services/admin/package-lock.json"
        "${project_name}-codelist:$repo_root/services/codelist/package-lock.json"
    )
    for pair in "${pairs[@]}"; do
        local image="${pair%%:*}"
        local lockfile="${pair##*:}"
        if [ -f "$lockfile" ]; then
            local hash
            hash=$(md5 -q "$lockfile" 2>/dev/null || md5sum "$lockfile" | cut -d' ' -f1)
            echo "$hash" > "$tmp_dir/${image}.lockfile-hash"
        fi
    done
}

# --- Seed helper ---

function wait_for_migrations() {
    local service=$1
    local max_attempts=30
    local attempt=0
    echo "Waiting for $service migrations to complete..."
    while [ $attempt -lt $max_attempts ]; do
        if dc exec "$service" sh -c 'npx prisma migrate status 2>&1 | grep -q "Database schema is up to date"'; then
            echo "$service migrations complete."
            return 0
        fi
        attempt=$((attempt + 1))
        sleep 2
    done
    echo "Warning: Timed out waiting for $service migrations."
    return 1
}

function run_seed() {
    echo
    echo "Pushing admin database schema..."
    dc exec admin npm run docker:push-db-schema

    echo "Setting up admin test datasources..."
    dc exec admin node build/test-data/setup-test-datasources

    wait_for_migrations registries

    echo "Seeding ICD-10 codes..."
    dc exec registries sh -c 'POSTGRES_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/registries" npm run seed-icd10'

    echo "Seeding ATC codes..."
    dc exec registries sh -c 'POSTGRES_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/registries" npm run seed-atc'

    echo
    echo "Data seeded successfully."
    echo
}

# --- CLAUDE.local.md port info ---

claude_local_md="$repo_root/CLAUDE.local.md"
marker_start="<!-- worktree-ports-start -->"
marker_end="<!-- worktree-ports-end -->"

function write_claude_ports() {
    local s=$1
    local offset=$(( s * 100 ))

    local block
    block=$(cat <<EOF
${marker_start}
## Worktree Ports (slot $s)

This worktree is running an isolated Docker stack. Use these ports instead of the defaults:

| Service | URL |
|---------|-----|
| Frontend | http://localhost:$(( 3001 + offset ))/en/registries |
| Router (GraphQL) | http://localhost:$(( 4000 + offset )) |
| Admin (GraphQL) | http://localhost:$(( 4004 + offset )) |
| Admin (gRPC) | localhost:$(( 50004 + offset )) |
| Codelist (gRPC) | localhost:$(( 50005 + offset )) |
| Registries (GraphQL) | http://localhost:$(( 4006 + offset )) |
| Registries (gRPC) | localhost:$(( 50006 + offset )) |
| Agent | http://localhost:$(( 4007 + offset )) |
| PostgreSQL | localhost:$(( 5432 + offset )) |
| MySQL | localhost:$(( 3336 + offset )) |

When opening the app in the browser, use port $(( 3001 + offset )).

## Running Tests

### Frontend unit tests (Vitest)

Run all unit tests:
\`\`\`bash
cd $repo_root/apps/main-frontend && npm test
\`\`\`

Run tests for a specific file:
\`\`\`bash
cd $repo_root/apps/main-frontend && npm test -- src/app/path/to/your.test.tsx
\`\`\`

Run tests for a specific directory:
\`\`\`bash
cd $repo_root/apps/main-frontend && npm test -- src/app/path/to/test-directory
\`\`\`

### Registries service tests (Jest)

Run all tests:
\`\`\`bash
cd $repo_root/services/registries && POSTGRES_URL="postgresql://postgres:postgres@localhost:$(( 5432 + offset ))/registries-test" npm run test
\`\`\`

Run tests for a specific file:
\`\`\`bash
cd $repo_root/services/registries && POSTGRES_URL="postgresql://postgres:postgres@localhost:$(( 5432 + offset ))/registries-test" npm run test -- src/path/to/your.test.ts
\`\`\`

Run tests for a specific directory:
\`\`\`bash
cd $repo_root/services/registries && POSTGRES_URL="postgresql://postgres:postgres@localhost:$(( 5432 + offset ))/registries-test" npm run test -- src/path/to/test-directory
\`\`\`

### Frontend E2E tests (Playwright)

Run all E2E tests:
\`\`\`bash
cd $repo_root/apps/main-frontend && FRONTEND_BASE_URL="http://localhost:$(( 3001 + offset ))" E2E_API_URL="http://localhost:$(( 4000 + offset ))" npx playwright test "src/app/.*/registries/.*\.spec\.tsx"
\`\`\`

Run E2E tests for a specific file:
\`\`\`bash
cd $repo_root/apps/main-frontend && FRONTEND_BASE_URL="http://localhost:$(( 3001 + offset ))" E2E_API_URL="http://localhost:$(( 4000 + offset ))" npx playwright test src/app/path/to/your.spec.tsx
\`\`\`

Run E2E tests for a specific directory:
\`\`\`bash
cd $repo_root/apps/main-frontend && FRONTEND_BASE_URL="http://localhost:$(( 3001 + offset ))" E2E_API_URL="http://localhost:$(( 4000 + offset ))" npx playwright test src/app/path/to/e2e-directory
\`\`\`
${marker_end}
EOF
    )

    # Remove existing block if present, then append
    remove_claude_ports 2>/dev/null
    if [ -f "$claude_local_md" ]; then
        printf '\n%s\n' "$block" >> "$claude_local_md"
    else
        printf '%s\n' "$block" > "$claude_local_md"
    fi
}

function remove_claude_ports() {
    if [ -f "$claude_local_md" ]; then
        # Remove the marker block (inclusive)
        if [[ "$OSTYPE" == darwin* ]]; then
            sed -i '' "/${marker_start}/,/${marker_end}/d" "$claude_local_md"
            # Remove trailing blank lines
            sed -i '' -e :a -e '/^\n*$/{$d;N;ba' -e '}' "$claude_local_md"
        else
            sed -i "/${marker_start}/,/${marker_end}/d" "$claude_local_md"
            # Remove trailing blank lines
            sed -i -e :a -e '/^\n*$/{$d;N;ba' -e '}' "$claude_local_md"
        fi
        # Remove file if empty
        if [ ! -s "$claude_local_md" ]; then
            rm -f "$claude_local_md"
        fi
    fi
}

# --- Prerequisites ---

function prerequisites_check() {
    check_docker
}

# --- Status ---

function show_status() {
    echo "Running worktree stacks:"
    echo

    local found=0
    for s in $(seq 1 9); do
        local container
        container=$(docker ps -q --filter "label=com.ledidi.worktree-slot=${s}" 2>/dev/null | head -1)
        if [ -n "$container" ]; then
            found=1
            local offset=$(( s * 100 ))
            local project
            project=$(docker inspect --format '{{index .Config.Labels "com.docker.compose.project"}}' "$container" 2>/dev/null)
            local count
            count=$(docker ps -q --filter "label=com.docker.compose.project=${project}" 2>/dev/null | wc -l | tr -d ' ')
            echo "  Slot $s — $project"
            echo "    Frontend:   http://localhost:$(( 3001 + offset ))/en"
            echo "    Router:     http://localhost:$(( 4000 + offset ))"
            echo "    Agent:      http://localhost:$(( 4007 + offset ))"
            echo "    Postgres:   localhost:$(( 5432 + offset ))"
            echo "    MySQL:      localhost:$(( 3336 + offset ))"
            echo "    Containers: $count"
            echo
        fi
    done

    if [ "$found" -eq 0 ]; then
        echo "  No worktree stacks running."
    fi
}

# --- Parse arguments ---

if [ "$#" -lt 1 ]; then
    usage
fi

for arg in "$@"; do
    case $arg in
    --up|--stop|--start|--down|--nuke|--status)
        if [ -n "$command" ]; then
            echo "Error: Only one command allowed" >&2
            exit 1
        fi
        command="${arg#--}"
        ;;
    --rebuild)
        rebuild=true
        ;;
    --slot=*)
        slot="${arg#*=}"
        ;;
    --help)
        usage
        ;;
    *)
        echo "Unknown argument: $arg"
        usage
        ;;
    esac
done

if [ -z "$command" ]; then
    usage
fi

# --- Execute ---

if [ "$command" = "status" ]; then
    show_status
    exit 0
fi

resolved_slot=$(resolve_slot)
offset=$(( resolved_slot * 100 ))

echo "Worktree slot: $resolved_slot (port offset: +$offset)"
echo "Project name:  $project_name"
echo "Frontend URL:  http://localhost:$(( 3001 + offset ))/en"
echo

prerequisites_check

worktree_services=$(available_services "main-frontend router router-autoupdate postgres mysql admin codelist registries agent")

if [ "$command" = "up" ]; then
    save_slot "$resolved_slot"
    # Needed so docker doesn't bind supergraph.graphql as a directory on clean checkouts
    if [ ! -f "$repo_root/services/apollo-router/supergraph.graphql" ]; then
        touch "$repo_root/services/apollo-router/supergraph.graphql"
    fi
    generate_override "$resolved_slot" > /dev/null
    # Auto-detect if images need rebuilding
    if [ "$rebuild" != true ]; then
        check_image_freshness "${project_name}-admin" "$repo_root/services/admin/package-lock.json"
        check_image_freshness "${project_name}-codelist" "$repo_root/services/codelist/package-lock.json"
    fi
    if [ "$rebuild" = true ]; then
        dc up --build -d --wait $worktree_services
    else
        dc up -d --wait $worktree_services
    fi

    save_lockfile_hashes

    run_seed
    write_claude_ports "$resolved_slot"

    echo "Stack is running at http://localhost:$(( 3001 + offset ))/en/registries"

elif [ "$command" = "stop" ]; then
    generate_override "$resolved_slot" > /dev/null
    dc stop

elif [ "$command" = "start" ]; then
    generate_override "$resolved_slot" > /dev/null
    dc up -d $worktree_services

elif [ "$command" = "down" ]; then
    generate_override "$resolved_slot" > /dev/null
    dc down
    remove_claude_ports

elif [ "$command" = "nuke" ]; then
    echo "This will remove all containers, volumes, and images for slot $resolved_slot."
    read -r -p "Are you sure? (y/N): " confirm
    echo
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        echo "Nuke operation cancelled."
        exit 0
    fi
    generate_override "$resolved_slot" > /dev/null
    dc down -v --rmi local --remove-orphans
    clear_saved_slot
    remove_claude_ports
    rm -rf "$tmp_dir"
    echo
    echo "Nuke operation completed."

else
    echo "Unknown command: $command"
    exit 1
fi
