#!/bin/bash

### Runs the full app stack from any worktree, isolated from other worktrees
### by port offsets and Docker project namespacing.
###
### Usage:
###   scripts/run-worktree.sh --up [--slot=N]
###   scripts/run-worktree.sh --down [--slot=N]
###   scripts/run-worktree.sh --nuke [--slot=N]
###   scripts/run-worktree.sh --status
###
### Each worktree gets a slot number (1-9) that determines its port offset.
### Slot 0 is reserved for the main repo's scripts/dev.

set -euo pipefail

script_dir=$(cd "$(dirname "$0")" && pwd)
repo_root="$(git rev-parse --show-toplevel)"

project_name="$(basename "$repo_root")"
tmp_dir="/Users/philip/work/tmp/dev-stacks/$project_name"

command=""
slot=""
rebuild=false

function usage() {
    echo "Usage: $0 --[up|stop|start|down|nuke|status] [--slot=N]"
    echo
    echo "Options:"
    echo "  --up                Create and start the worktree stack (reuses existing images)"
    echo "  --stop              Stop running containers without removing them"
    echo "  --start             Start previously stopped containers"
    echo "  --down              Stop and remove containers and networks"
    echo "  --nuke              Remove all containers, volumes, and images for this worktree"
    echo "  --status            List all running worktree stacks"
    echo "  --rebuild           Rebuild container images before starting"
    echo "  --slot=N            Slot number (1-9). Auto-assigned (next available) if omitted."
    echo "  --help              Show this help message"
    exit 1
}

# --- Slot management ---

slot_file="$tmp_dir/worktree-slot"

function is_slot_in_use() {
    local s=$1
    local containers
    containers=$(docker ps -q --filter "label=com.ledidi.worktree-slot=${s}" 2>/dev/null)
    [ -n "$containers" ]
}

function next_available_slot() {
    for s in $(seq 1 9); do
        if ! is_slot_in_use "$s"; then
            echo "$s"
            return
        fi
    done
    echo "Error: All slots (1-9) are in use." >&2
    exit 1
}

function save_slot() {
    mkdir -p "$tmp_dir"
    echo "$1" > "$slot_file"
}

function read_saved_slot() {
    if [ -f "$slot_file" ]; then
        cat "$slot_file"
    else
        echo ""
    fi
}

function clear_saved_slot() {
    rm -f "$slot_file"
}

function resolve_slot() {
    if [ -n "$slot" ]; then
        # Explicit --slot=N provided
        if ! [[ "$slot" =~ ^[1-9]$ ]]; then
            echo "Error: --slot must be a number between 1 and 9."
            exit 1
        fi
        echo "$slot"
        return
    fi

    # Check for a previously saved slot
    local saved
    saved=$(read_saved_slot)
    if [ -n "$saved" ]; then
        echo "$saved"
        return
    fi

    # Auto-assign the next available slot
    if [ "$command" = "up" ]; then
        next_available_slot
    else
        echo "Error: No slot assigned yet. Run --up first or pass --slot=N." >&2
        exit 1
    fi
}

# --- Override file generation ---

function generate_override() {
    local s=$1
    local offset=$(( s * 100 ))
    mkdir -p "$tmp_dir"
    local override_file="$tmp_dir/docker-compose.worktree.yml"
    local router_config="$tmp_dir/router.docker.worktree.yaml"

    # Generate a worktree-specific router config with the correct CORS origin
    sed "s|http://localhost:3001|http://localhost:$(( 3001 + offset ))|g" \
        "$repo_root/services/apollo-router/router.docker.yaml" > "$router_config"

    cat > "$override_file" <<YAML
# Auto-generated by run-worktree.sh (slot $s, offset $offset)
# Do not edit — regenerated on each run.

services:
  main-frontend:
    labels:
      com.ledidi.worktree-slot: "${s}"
    environment:
      - VITE_APP_URL=http://localhost:$(( 3001 + offset ))
      - VITE_GRAPHQL_URI=http://localhost:$(( 4000 + offset ))
      - VITE_SURVEY_URL=http://localhost:$(( 3001 + offset ))/surveys
    ports: !override
      - "$(( 3001 + offset )):3001"

  router:
    volumes: !override
      - $repo_root/services/apollo-router/supergraph.graphql:/dist/schema/supergraph.graphql
      - $tmp_dir/router.docker.worktree.yaml:/dist/config/router.yaml
    ports: !override
      - "$(( 4000 + offset )):4000"

  postgres:
    ports: !override
      - "$(( 5432 + offset )):5432"

  mysql:
    ports: !override
      - "$(( 3336 + offset )):3306"

  router-autoupdate:
    image: ledidi-shared-router-autoupdate
    pull_policy: build

  admin:
    image: ledidi-shared-admin
    pull_policy: build
    depends_on: !override
      mysql:
        condition: service_healthy
    ports: !override
      - "$(( 4004 + offset )):4000"
      - "$(( 50004 + offset )):50051"
      - "$(( 9004 + offset )):9229"

  codelist:
    image: ledidi-shared-codelist
    pull_policy: build
    ports: !override
      - "$(( 4005 + offset )):4000"
      - "$(( 50005 + offset )):50051"

  registries:
    ports: !override
      - "$(( 4006 + offset )):4000"
      - "$(( 50006 + offset )):50051"

networks:
  default:
    name: default-network-wt-${s}
    driver: bridge

YAML

    # Conditionally add services that may not exist in all branches
    if grep -qE '^\s+agent:' "$repo_root/docker-compose.yml" 2>/dev/null; then
        cat >> "$override_file" <<AGENT_YAML

  agent:
    ports: !override
      - "$(( 4007 + offset )):4000"
AGENT_YAML
    fi

    echo "$override_file"
}

# --- Compose service filtering ---

function available_services() {
    local all_services="$1"
    local result=""
    for svc in $all_services; do
        if grep -qE "^\s+${svc}:" "$repo_root/docker-compose.yml" 2>/dev/null; then
            result="$result $svc"
        fi
    done
    echo "$result"
}

# --- Docker compose helper ---

function dc() {
    COMPOSE_PROJECT_NAME="$project_name" \
        docker compose \
        -f "$repo_root/docker-compose.yml" \
        -f "$tmp_dir/docker-compose.worktree.yml" \
        "$@"
}

# --- Seed helper ---

function run_seed() {
    echo
    echo "Seeding ATC codes in registries database..."
    dc exec -e POSTGRES_URL="postgresql://postgres:postgres@postgres:5432/registries" registries npm run seed-atc
    echo
    echo "Data seeded successfully."
    echo
}

# --- CLAUDE.local.md port info ---

claude_local_md="$repo_root/CLAUDE.local.md"
marker_start="<!-- worktree-ports-start -->"
marker_end="<!-- worktree-ports-end -->"

function write_claude_ports() {
    local s=$1
    local offset=$(( s * 100 ))

    local block
    block=$(cat <<EOF
${marker_start}
## Worktree Ports (slot $s)

This worktree is running an isolated Docker stack. Use these ports instead of the defaults:

| Service | URL |
|---------|-----|
| Frontend | http://localhost:$(( 3001 + offset ))/en |
| Router (GraphQL) | http://localhost:$(( 4000 + offset )) |
| Admin (GraphQL) | http://localhost:$(( 4004 + offset )) |
| Admin (gRPC) | localhost:$(( 50004 + offset )) |
| Codelist (gRPC) | localhost:$(( 50005 + offset )) |
| Registries (GraphQL) | http://localhost:$(( 4006 + offset )) |
| Registries (gRPC) | localhost:$(( 50006 + offset )) |
| Agent | http://localhost:$(( 4007 + offset )) |
| PostgreSQL | localhost:$(( 5432 + offset )) |
| MySQL | localhost:$(( 3336 + offset )) |

When running E2E tests or opening the app in the browser, use port $(( 3001 + offset )) instead of 3001.
${marker_end}
EOF
    )

    # Remove existing block if present, then append
    remove_claude_ports 2>/dev/null
    if [ -f "$claude_local_md" ]; then
        printf '\n%s\n' "$block" >> "$claude_local_md"
    else
        printf '%s\n' "$block" > "$claude_local_md"
    fi
}

function remove_claude_ports() {
    if [ -f "$claude_local_md" ]; then
        # Remove the marker block (inclusive)
        sed -i '' "/${marker_start}/,/${marker_end}/d" "$claude_local_md"
        # Remove trailing blank lines
        sed -i '' -e :a -e '/^\n*$/{$d;N;ba' -e '}' "$claude_local_md"
        # Remove file if empty
        if [ ! -s "$claude_local_md" ]; then
            rm -f "$claude_local_md"
        fi
    fi
}

# --- Prerequisites ---

function prerequisites_check() {
    if ! command -v docker >/dev/null 2>&1; then
        echo "Docker is not installed. Please install Docker to proceed."
        exit 1
    fi
}

# --- Status ---

function show_status() {
    echo "Running worktree stacks:"
    echo

    local found=0
    for s in $(seq 1 9); do
        local container
        container=$(docker ps -q --filter "label=com.ledidi.worktree-slot=${s}" 2>/dev/null | head -1)
        if [ -n "$container" ]; then
            found=1
            local offset=$(( s * 100 ))
            local project
            project=$(docker inspect --format '{{index .Config.Labels "com.docker.compose.project"}}' "$container" 2>/dev/null)
            local count
            count=$(docker ps -q --filter "label=com.docker.compose.project=${project}" 2>/dev/null | wc -l | tr -d ' ')
            echo "  Slot $s — $project"
            echo "    Frontend:   http://localhost:$(( 3001 + offset ))/en"
            echo "    Router:     http://localhost:$(( 4000 + offset ))"
            echo "    Agent:      http://localhost:$(( 4007 + offset ))"
            echo "    Postgres:   localhost:$(( 5432 + offset ))"
            echo "    MySQL:      localhost:$(( 3336 + offset ))"
            echo "    Containers: $count"
            echo
        fi
    done

    if [ "$found" -eq 0 ]; then
        echo "  No worktree stacks running."
    fi
}

# --- Parse arguments ---

if [ "$#" -lt 1 ]; then
    usage
fi

for arg in "$@"; do
    case $arg in
    --up)
        command="up"
        ;;
    --stop)
        command="stop"
        ;;
    --start)
        command="start"
        ;;
    --down)
        command="down"
        ;;
    --nuke)
        command="nuke"
        ;;
    --status)
        command="status"
        ;;
    --rebuild)
        rebuild=true
        ;;
    --slot=*)
        slot="${arg#*=}"
        ;;
    --help)
        usage
        ;;
    *)
        echo "Unknown argument: $arg"
        usage
        ;;
    esac
done

if [ -z "$command" ]; then
    usage
fi

# --- Execute ---

if [ "$command" = "status" ]; then
    show_status
    exit 0
fi

resolved_slot=$(resolve_slot)
offset=$(( resolved_slot * 100 ))

echo "Worktree slot: $resolved_slot (port offset: +$offset)"
echo "Project name:  $project_name"
echo "Frontend URL:  http://localhost:$(( 3001 + offset ))/en"
echo

prerequisites_check

worktree_services=$(available_services "main-frontend router router-autoupdate postgres mysql admin codelist registries agent")

if [ "$command" = "up" ]; then
    save_slot "$resolved_slot"
    # Needed so docker doesn't bind supergraph.graphql as a directory on clean checkouts
    if [ ! -f "$repo_root/services/apollo-router/supergraph.graphql" ]; then
        touch "$repo_root/services/apollo-router/supergraph.graphql"
    fi
    generate_override "$resolved_slot" > /dev/null
    if [ "$rebuild" = true ]; then
        dc up --build -d --wait $worktree_services
    else
        dc up -d --wait $worktree_services
    fi

    run_seed
    write_claude_ports "$resolved_slot"

    echo "Stack is running at http://localhost:$(( 3001 + offset ))/en"

elif [ "$command" = "stop" ]; then
    generate_override "$resolved_slot" > /dev/null
    dc stop

elif [ "$command" = "start" ]; then
    generate_override "$resolved_slot" > /dev/null
    dc start

elif [ "$command" = "down" ]; then
    generate_override "$resolved_slot" > /dev/null
    dc down
    remove_claude_ports

elif [ "$command" = "nuke" ]; then
    echo "This will remove all containers, volumes, and images for slot $resolved_slot."
    read -p "Are you sure? (y/N): " confirm
    echo
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        echo "Nuke operation cancelled."
        exit 0
    fi
    generate_override "$resolved_slot" > /dev/null
    dc down -v --rmi local --remove-orphans
    clear_saved_slot
    remove_claude_ports
    rm -rf "$tmp_dir"
    echo
    echo "Nuke operation completed."

else
    echo "Unknown command: $command"
    exit 1
fi
