#!/bin/bash

### Runs the app stack from the main repo with the same service set
### as the worktree script.
###
### Usage:
###   scripts/run-main.sh --up
###   scripts/run-main.sh --stop
###   scripts/run-main.sh --start
###   scripts/run-main.sh --down
###   scripts/run-main.sh --nuke
###   scripts/run-main.sh --rebuild

set -euo pipefail

function check_docker() {
    if ! command -v docker &>/dev/null; then
        echo "Error: Docker not installed" >&2
        exit 1
    fi
    if ! docker info &>/dev/null; then
        echo "Error: Docker daemon not running" >&2
        exit 1
    fi
}

if ! git rev-parse --show-toplevel &>/dev/null; then
    echo "Error: Not inside a git repository" >&2
    exit 1
fi
repo_root="$(git rev-parse --show-toplevel)"
project_name="$(basename "$repo_root")"
tmp_dir="${DEV_STACKS_DIR:-$HOME/work/tmp/dev-stacks}/$project_name"

command=""
rebuild=false

function usage() {
    echo "Usage: $0 --[up|stop|start|down|nuke] [--rebuild]"
    echo
    echo "Options:"
    echo "  --up                Create and start the stack (reuses existing images)"
    echo "  --stop              Stop running containers without removing them"
    echo "  --start             Start previously stopped containers"
    echo "  --down              Stop and remove containers and networks"
    echo "  --nuke              Remove all containers, volumes, and images"
    echo "  --rebuild           Rebuild container images before starting"
    echo "  --help              Show this help message"
    exit 1
}

# --- Override file generation ---

function generate_override() {
    mkdir -p "$tmp_dir"
    local override_file="$tmp_dir/docker-compose.dev.yml"

    cat > "$override_file" <<'YAML'
# Auto-generated by run-main.sh
# Do not edit — regenerated on each run.

services:
  admin:
    depends_on: !override
      mysql:
        condition: service_healthy

YAML

    echo "$override_file"
}

# --- Docker compose helper ---

function dc() {
    docker compose \
        -f "$repo_root/docker-compose.yml" \
        -f "$tmp_dir/docker-compose.dev.yml" \
        "$@"
}

# --- Lockfile freshness check ---

function check_image_freshness() {
    local image=$1
    local lockfile=$2

    if ! docker image inspect "$image" &>/dev/null; then
        return  # Image doesn't exist yet; will be built on first up
    fi

    if [ ! -f "$lockfile" ]; then
        return
    fi

    local current_hash
    current_hash=$(md5 -q "$lockfile" 2>/dev/null || md5sum "$lockfile" | cut -d' ' -f1)

    local hash_file="$tmp_dir/${image}.lockfile-hash"
    local stored_hash=""
    if [ -f "$hash_file" ]; then
        stored_hash=$(cat "$hash_file")
    fi

    if [ "$current_hash" != "$stored_hash" ]; then
        echo "Dependencies changed for $image — forcing rebuild."
        rebuild=true
    fi
}

function save_lockfile_hashes() {
    local pairs=(
        "${project_name}-admin:$repo_root/services/admin/package-lock.json"
        "${project_name}-codelist:$repo_root/services/codelist/package-lock.json"
    )
    for pair in "${pairs[@]}"; do
        local image="${pair%%:*}"
        local lockfile="${pair##*:}"
        if [ -f "$lockfile" ]; then
            local hash
            hash=$(md5 -q "$lockfile" 2>/dev/null || md5sum "$lockfile" | cut -d' ' -f1)
            echo "$hash" > "$tmp_dir/${image}.lockfile-hash"
        fi
    done
}

# --- Seed helper ---

function wait_for_migrations() {
    local service=$1
    local max_attempts=30
    local attempt=0
    echo "Waiting for $service migrations to complete..."
    while [ $attempt -lt $max_attempts ]; do
        if dc exec "$service" sh -c 'npx prisma migrate status 2>&1 | grep -q "Database schema is up to date"'; then
            echo "$service migrations complete."
            return 0
        fi
        attempt=$((attempt + 1))
        sleep 2
    done
    echo "Warning: Timed out waiting for $service migrations."
    return 1
}

function run_seed() {
    echo
    echo "Pushing admin database schema..."
    dc exec admin npm run docker:push-db-schema

    echo "Setting up admin test datasources..."
    dc exec admin node build/test-data/setup-test-datasources

    wait_for_migrations registries

    echo "Seeding ICD-10 codes..."
    dc exec registries sh -c 'POSTGRES_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/registries" npm run seed-icd10'

    echo "Seeding ATC codes..."
    dc exec registries sh -c 'POSTGRES_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/registries" npm run seed-atc'

    echo
    echo "Data seeded successfully."
    echo
}

# --- Prerequisites ---

function prerequisites_check() {
    check_docker
}

# --- Parse arguments ---

if [ "$#" -lt 1 ]; then
    usage
fi

for arg in "$@"; do
    case $arg in
    --up|--stop|--start|--down|--nuke)
        if [ -n "$command" ]; then
            echo "Error: Only one command allowed" >&2
            exit 1
        fi
        command="${arg#--}"
        ;;
    --rebuild)
        rebuild=true
        ;;
    --help)
        usage
        ;;
    *)
        echo "Unknown argument: $arg"
        usage
        ;;
    esac
done

if [ -z "$command" ]; then
    usage
fi

# --- Execute ---

prerequisites_check

dev_services="main-frontend router router-autoupdate postgres mysql admin codelist registries"

if [ "$command" = "up" ]; then
    if [ ! -f "$repo_root/services/apollo-router/supergraph.graphql" ]; then
        touch "$repo_root/services/apollo-router/supergraph.graphql"
    fi
    generate_override > /dev/null
    # Auto-detect if images need rebuilding
    if [ "$rebuild" != true ]; then
        check_image_freshness "${project_name}-admin" "$repo_root/services/admin/package-lock.json"
        check_image_freshness "${project_name}-codelist" "$repo_root/services/codelist/package-lock.json"
    fi
    if [ "$rebuild" = true ]; then
        dc up --build -d --wait $dev_services
    else
        dc up -d --wait $dev_services
    fi

    save_lockfile_hashes

    run_seed

    echo "Stack is running at http://localhost:3001/en/registries"

elif [ "$command" = "stop" ]; then
    generate_override > /dev/null
    dc stop

elif [ "$command" = "start" ]; then
    generate_override > /dev/null
    dc up -d $dev_services

elif [ "$command" = "down" ]; then
    generate_override > /dev/null
    dc down

elif [ "$command" = "nuke" ]; then
    echo "This will remove all containers, volumes, and images."
    read -r -p "Are you sure? (y/N): " confirm
    echo
    if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
        echo "Nuke operation cancelled."
        exit 0
    fi
    generate_override > /dev/null
    dc down -v --rmi local --remove-orphans
    rm -rf "$tmp_dir"
    echo
    echo "Nuke operation completed."

else
    echo "Unknown command: $command"
    exit 1
fi
